# Generated by Django 4.2.3 on 2023-08-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_chat_limit",
            field=models.IntegerField(default=6),
        ),
    ]
